<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UniversityOrganization" nsURI="http://it.gssi/university_organization/v1"
    nsPrefix="UniversityOrganization">
  <eClassifiers xsi:type="ecore:EClass" name="UniversityOrganizationModel" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="departments" upperBound="-1"
        eType="#//Department" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facultyMembers" upperBound="-1"
        eType="#//FacultyMember" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchGroups" upperBound="-1"
        eType="#//ResearchGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="director" lowerBound="1"
        eType="#//FacultyMember"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResearchGroup" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="openPosition" upperBound="-1"
        eType="#//Position" eOpposite="#//Position/researchGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacultyMember" eSuperTypes="#//AcademicPeople">
    <eStructuralFeatures xsi:type="ecore:EReference" name="positions" upperBound="-1"
        eType="#//Position" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" lowerBound="1"
        eType="#//Department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchGroup" eType="#//ResearchGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guest" eType="#//Guest"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchGroup" lowerBound="1"
        eType="#//ResearchGroup" eOpposite="#//ResearchGroup/openPosition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guest" eSuperTypes="#//AcademicPeople">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="affiliation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="remuneration" lowerBound="1"
        eType="#//Remuneration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invitingPerson" eType="#//FacultyMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="departmentDirector" eType="#//FacultyMember"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcademicPeople" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grade" eType="#//AcademicGrade"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortBio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titlePrefix" eType="#//TitlePrefix"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lecture" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Seminar" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="venue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remoteLink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResearchCollaboration" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Remuneration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelRefund" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="perDiems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hotelPrepaid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remunerationTotal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//PaymentStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AcademicGrade">
    <eLiterals name="FullProfessor"/>
    <eLiterals name="AssociateProfessor" value="1"/>
    <eLiterals name="Researcher" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PaymentStatus">
    <eLiterals name="Todo"/>
    <eLiterals name="InProgress" value="1"/>
    <eLiterals name="ReadyToBeSent" value="2"/>
    <eLiterals name="Done" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TitlePrefix">
    <eLiterals name="Prof"/>
    <eLiterals name="Dr" value="1"/>
    <eLiterals name="Mr" value="2"/>
    <eLiterals name="Mrs" value="3"/>
  </eClassifiers>
</ecore:EPackage>
