<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PersonRemuneration" nsURI="http://it.gssi/person_remuneration/v1"
    nsPrefix="PersonRemuneration">
  <eClassifiers xsi:type="ecore:EClass" name="PersonRemunerationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Remuneration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="payment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//RemunerationStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="remuneration" eType="#//Remuneration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RemunerationStatus">
    <eLiterals name="ToDo" literal="ToDo"/>
    <eLiterals name="InProgress" value="1" literal="InProgress"/>
    <eLiterals name="Done" value="2" literal="Done"/>
  </eClassifiers>
</ecore:EPackage>
